### ISSUE TITLE
Recurring jobs are failing after 1 day

### ISSUE THREAD

**Issue by naveenmora** [JustinAiken/active_scheduler#8]
We are running recurring jobs continuously  for every 30s but it is working for one day on production after one if schedule the job its not working and not executing the job.

Please help me ASAP.

**Comment by JustinAiken** [comment]
It sounds like this more likely an issue with [Resque Scheduler](https://github.com/resque/resque-scheduler)... All this gem does is convert the standard schedule format into ActiveJob-ready ones

Try doing `bundle exec rails runner "puts Resque.schedule.inspect"` on your production server before and after it stops working, see if they're the same... 

Also make sure that `Resque::Scheduler.dynamic` returns `false`; if it's not, you have something overwriting it..
